/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Cw721Hero.types";
import * as _1 from "./Cw721Hero.client";
export namespace contracts {
  export const Cw721Hero = { ..._0,
    ..._1
  };
}